import type { AiMessageStreaming } from '@/components/agent/agent-sidebar/types'

export const sampleAiStreamingResponse: AiMessageStreaming[] = [
  // ── EMPTY START ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── REASONING CHUNKS ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: 'The',
    reasoning: 'The',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: ' user is asking about "nividia latest creation',
    reasoning: ' user is asking about "nividia latest creation',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: '" - which is likely a misspelling of "',
    reasoning: '" - which is likely a misspelling of "',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: 'NVIDIA". They want to know about NVIDIA\'s latest',
    reasoning: 'NVIDIA". They want to know about NVIDIA\'s latest',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: ' product or creation. This is a question that requires current',
    reasoning: ' product or creation. This is a question that requires current',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: ' information, so I should use the search_agent',
    reasoning: ' information, so I should use the search_agent',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content: ' tool to get up-to-date information about NVIDIA\'s',
    reasoning: ' tool to get up-to-date information about NVIDIA\'s',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {
    reasoning_content:
    ' latest announcements or products.\n\nLet me search for information',
    reasoning:
    ' latest announcements or products.\n\nLet me search for information',
    _reasoning_api_fields: ['reasoning_content', 'reasoning'],
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── RESOLVED TOOL CALL (same chunk has tool_calls + tool_call_chunks) ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {},
    response_metadata: {
    finish_reason: 'tool_calls',
    model_name: 'stepfun-ai/step-3.5-flash',
      },
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [
    {
    name: 'search_agent',
    args: { query: 'NVIDIA latest product creation 2024' },
    id: 'call_bcf1128768104bee9559ad61',
    type: 'tool_call',
        },
    ],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [
    {
    name: 'search_agent',
    args: '{"query": "NVIDIA latest product creation 2024"}',
    id: 'call_bcf1128768104bee9559ad61',
    index: 0,
    type: 'tool_call_chunk',
        },
    ],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── USAGE METADATA CHUNK ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: { input_tokens: 1290, output_tokens: 113, total_tokens: 1403 },
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── LAST POSITION CHUNK ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-c93b-7f72-9df9-6e3fb59aed4f',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: 'last',
    role: 'assistant',
    },
  },

  // ── TOOL MESSAGE (search_agent result) ──
  {
    node: 'chat_node',
    message: {
    type: 'tool',
    content: JSON.stringify([
    {
    url: 'https://www.nvidia.com/en-us/',
    title: 'World Leader in AI Computing',
    description:
    'NVIDIA RTX Spark superchip announced at GTC Taipei. Features Blackwell RTX GPU with 6,144 CUDA cores, 1 petaflop AI performance, up to 128GB unified memory.',
    text: 'NVIDIA RTX Spark is a new superchip that reinvents Windows PCs for the era of personal AI agents. Available this fall from ASUS, Dell, HP, Lenovo, Microsoft Surface and MSI.',
        },
    {
    url: 'https://nvidianews.nvidia.com/news/nvidia-microsoft-windows-pcs-agents-rtx-spark',
    title: 'NVIDIA and Microsoft Reinvent Windows PCs for the Age of Personal AI',
    description:
    'NVIDIA RTX Spark powers the first Windows PCs purpose-built for personal agents.',
    text: 'RTX Spark features NVIDIA Blackwell RTX GPU, NVLink-C2C interconnect, and 20-core NVIDIA Grace CPU. Collaboration with Microsoft for secure on-device AI agents.',
        },
    ]),
    additional_kwargs: {},
    response_metadata: {},
    name: 'search_agent',
    id: '227b31ef-48f9-44f9-8b9e-5dffa0b1a768',
    tool_call_id: 'call_bcf1128768104bee9559ad61',
    artifact: null,
    status: 'success',
    },
  },

  // ── SECOND RUN: first empty chunk ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── CONTENT CHUNKS (after tool result) ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' on the search results, NVIDIA\'s latest major creation appears',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' to be the **NVIDIA RTX Spark™**',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' superchip, which was announced recently (appears',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' to be at GTC Taipei). This is a',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' groundbreaking new chip designed specifically for Windows PCs in the era',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' of personal AI agents.\n\nLet me provide the user with',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' a concise summary of what RTX Spark is and',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── CHUNK WITH BOTH REASONING + CONTENT (transition/</think>) ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' why it\'s significant.\n</think>\nNVIDIA\'s latest',
    additional_kwargs: {
    reasoning_content: 'why it\'s significant.',
      },
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },

  // ── FINAL CONTENT CHUNKS ──
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' major creation is **NVIDIA RTX Spark™',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: '**, a revolutionary superchip announced at GTC Taipei',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' that reinvents Windows PCs for the era of personal',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
  {
    node: 'chat_node',
    message: {
    type: 'AIMessageChunk',
    content: ' AI agents.\n\n**Key Features:**\n\n- **1',
    additional_kwargs: {},
    response_metadata: {},
    name: null,
    id: 'lc_run--019eb06e-dd5e-78c2-b6b6-255643f119f4',
    tool_calls: [],
    invalid_tool_calls: [],
    usage_metadata: null,
    tool_call_chunks: [],
    chunk_position: null,
    role: 'assistant',
    },
  },
]
