import UserSidebar from "@/components/UserSidebar";
import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import UserHeader from "@/components/UserHeader";
import { Provider } from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<main className="min-h-dvh flex">
  <Provider>
    <SidebarProvider>
      <UserSidebar />
      <div className="flex flex-col flex-1">
        <UserHeader />
        <div className="flex-1">
          {children}
        </div>
      </div>
    </SidebarProvider>
  </Provider>
</main>

  );
}
